# 주석은 똑같다.
mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name: madang

  datasource:
    url: jdbc:mariadb://localhost/madang_spring
    username: root
    password: green502

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    default-model-expand-depth: 2
    default-models-expand-depth: -1
    display-request-duration: true
    operations-sorter: method
    path: /swagger